# ===============================
# НАСТРОЙКИ СЕТИ
# ===============================
network:
  rpc_url: "https://ethereum-rpc.publicnode.com" # RPC URL для подключения к сети Ethereum
  chain_id: 1 # Chain ID для Ethereum Mainnet (1 = mainnet, 11155111 = Sepolia testnet)

# ===============================
# НАСТРОЙКИ ТРАНЗАКЦИЙ
# ===============================
transaction:
  gas_limit: 21000 # Стандартный лимит газа для отправки нативного токена (21000 для ETH)
  gas_price_gwei: 0.9 # Цена газа в Gwei (используется если use_dynamic_gas = false)
  use_dynamic_gas: true # Использовать динамическое определение цены газа из сети
  gas_price_multiplier: 1.1 # Множитель для цены газа (для безопасности, 1.1 = +10%)
  
  # НАСТРОЙКИ СЛУЧАЙНОГО ОСТАТКА НА КОШЕЛЬКЕ
  random_remaining_balance_eth:
    min: 0.000004 # Минимальный случайный остаток в ETH
    max: 0.000008 # Максимальный случайный остаток в ETH

# ===============================
# НАСТРОЙКИ ВЫПОЛНЕНИЯ
# ===============================
execution:
  max_concurrent: 1 # Максимальное количество одновременных транзакций
  retry_count: 4 # Количество попыток при ошибке транзакции
  
  # НАСТРОЙКИ СЛУЧАЙНОЙ ЗАДЕРЖКИ МЕЖДУ ТРАНЗАКЦИЯМИ
  random_delay_range:
    min: 66 # Минимальная случайная задержка в секундах
    max: 88 # Максимальная случайная задержка в секундах
  
  # НАСТРОЙКИ ЗАДЕРЖКИ ДЛЯ ПРОПУЩЕННЫХ АККАУНТОВ
  skipped_account_delay: 2 # Задержка после пропущенного аккаунта в секундах
  
  # НАСТРОЙКИ ПЕРЕМЕШИВАНИЯ КОШЕЛЬКОВ
  shuffle_wallets: true # Перемешивать кошельки перед отправкой (с сохранением соответствия)
  
  show_progress: true # Показывать прогресс выполнения во время работы
  detailed_stats: true # Показывать детальную статистику по аккаунтам в конце

# ===============================
# НАСТРОЙКИ ПРОВЕРКИ БАЛАНСА
# ===============================
balance_check:
  enabled: true # Включить/выключить проверку минимального баланса перед отправкой
  minimum_balance: 0.00004 # Минимальный баланс в ETH для выполнения транзакции
  skip_message: "Аккаунт пропущен: недостаточный баланс ETH" # Сообщение при пропуске аккаунта

# ===============================
# НАСТРОЙКИ МОНИТОРИНГА ГАЗА
# ===============================
gas_monitor:
  enabled: true # Включить/выключить мониторинг цены газа
  max_gas_price_gwei: 1 # Максимальная цена газа в Gwei (если выше - ждем снижения)
  check_interval: 22 # Интервал проверки цены газа в секундах
  max_wait_time: 183000 # Максимальное время ожидания снижения газа в секундах (5 часов)
  notification_interval: 5 # Интервал уведомлений о высоком газе в секундах (50 минут)

# ===============================
# НАСТРОЙКИ БЛОКЧЕЙН-ЭКСПЛОРЕРА
# ===============================
explorer:
  base_url: "https://etherscan.io/tx/" # Базовый URL для создания ссылок на транзакции